platform:ios,'8.0'
target:'shopky' do
pod 'AFNetworking', '~>3.0.0'
pod 'JPFPSStatus'
pod 'GQGesVCTransition'
pod 'Masonry'
pod 'PPNetworkHelper'
pod 'SDCycleScrollView'
pod 'JSONModel'
pod 'MJRefresh'
use_frameworks!
pod 'LTScrollView'
pod 'FMDB'
pod 'SVProgressHUD'
pod 'TZImagePickerController'
pod 'MJExtension'
pod 'PPNumberButton'
pod 'PPBadgeView'
pod 'IQKeyboardManager'
pod 'AMapLocation-NO-IDFA'
end
